#
# Makefil
#
# $Revision$
# $LastChangedDate$
#

all: examples

examples:
	@ $(MAKE) -C exam01 
	@ $(MAKE) -C exam02 
	@ $(MAKE) -C exam03 
	@ $(MAKE) -C exam04 
	@ $(MAKE) -C exam05 
	@ $(MAKE) -C exam06 
	@ $(MAKE) -C exam07 
	@ $(MAKE) -C exam08 
	@ $(MAKE) -C exam09 

clean: clean-all

clear: clean-all

clean-all:
	@ $(MAKE) -C exam01 clean-all
	@ $(MAKE) -C exam02 clean-all
	@ $(MAKE) -C exam03 clean-all
	@ $(MAKE) -C exam04 clean-all
	@ $(MAKE) -C exam05 clean-all
	@ $(MAKE) -C exam06 clean-all
	@ $(MAKE) -C exam07 clean-all
	@ $(MAKE) -C exam08 clean-all
	@ $(MAKE) -C exam09 clean-all

